import { useEffect, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import './App.css'

type User = { username: string; email?: string | null }
type Profile = { creator_name: string | null; niche: string | null; platforms: string[]; region: string | null; languages?: string[]; audience_description?: string | null; audience_size: number | null; average_views: number | null; engagement_rate: number | null }
type Conversation = { session_id: string; created_at: string }
type Message = { role: 'user' | 'assistant'; content: string; created_at?: string }
type ResponsePayload = { text?: string; markdown?: string; links?: string[] }
type Page = 'overview' | 'opportunities' | 'research' | 'fit' | 'conversations' | 'profile' | 'settings'

const storage = { token: 'dealpilot.token', session: 'dealpilot.session' }
const emptyProfile: Profile = { creator_name: '', niche: '', platforms: [], region: '', audience_size: null, average_views: null, engagement_rate: null }

async function request<T>(path: string, options: RequestInit = {}): Promise<T> { const response = await fetch(path, { ...options, headers: { ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || 'Something went wrong. Please try again.'); return body as T }
function authHeaders() { return { Authorization: `Bearer ${localStorage.getItem(storage.token) || ''}` } }
function responseText(payload: ResponsePayload | string) { return typeof payload === 'string' ? payload : payload.markdown || payload.text || '' }
function profileForForm(profile: Profile): Profile { return { ...profile, creator_name: profile.creator_name || '', niche: profile.niche || '', region: profile.region || '', platforms: profile.platforms || [] } }
function escapeHtml(value: string) { return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;') }
function inlineMarkdown(value: string) { return escapeHtml(value).replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g, '<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>').replace(/`([^`]+)`/g, '<code>$1</code>').replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>').replace(/\*([^*]+)\*/g, '<em>$1</em>').replace(/(https?:\/\/[^\s<>'")\]]+)/g, '<a href="$1" target="_blank" rel="noopener noreferrer">$1</a>').replace(/\n/g, '<br />') }
function markdownHtml(markdown: string) { return markdown.replace(/\r\n/g, '\n').trim().split(/\n{2,}/).filter(Boolean).map((block) => { const lines = block.split('\n'); if (lines.every((line) => /^[-*]\s+/.test(line))) return `<ul>${lines.map((line) => `<li>${inlineMarkdown(line.replace(/^[-*]\s+/, ''))}</li>`).join('')}</ul>`; if (lines.every((line) => /^\d+\.\s+/.test(line))) return `<ol>${lines.map((line) => `<li>${inlineMarkdown(line.replace(/^\d+\.\s+/, ''))}</li>`).join('')}</ol>`; return `<p>${inlineMarkdown(block)}</p>` }).join('') || '<p></p>' }

function Logo() { return <div className="logo">Deal<span>Pilot</span></div> }
function Icon({ children }: { children: ReactNode }) { return <span className="nav-icon" aria-hidden="true">{children}</span> }
function DisabledButton({ children, className = 'button secondary' }: { children: ReactNode; className?: string }) { return <button className={className} disabled title="This action will be connected to the backend later">{children}</button> }

function AuthScreen({ onLogin }: { onLogin: (user: User) => void }) {
  const [mode, setMode] = useState<'login' | 'signup'>('login'); const [form, setForm] = useState({ username: '', email: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { if (mode === 'signup') await request('/auth/signup', { method: 'POST', body: JSON.stringify({ username: form.username.trim(), email: form.email.trim() || null, password: form.password }) }); const login = await request<{ access_token: string }>('/auth/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ username: form.username.trim(), password: form.password }) }); localStorage.setItem(storage.token, login.access_token); onLogin(await request<User>('/auth/me', { headers: authHeaders() })) } catch (err) { setError(err instanceof Error ? err.message : 'Unable to sign in') } finally { setBusy(false) } }
  return <main className="auth-screen"><section className="auth-visual"><Logo /><div className="visual-copy"><span className="kicker">Creator partnership intelligence</span><h1>Find the next right deal.</h1><p>Research brands, surface timely opportunities, and make confident partnership decisions from one focused deal desk.</p></div><span className="visual-foot">Private, account-based workspace</span></section><section className="auth-form"><div className="auth-tabs"><button className={mode === 'login' ? 'active' : ''} onClick={() => setMode('login')}>Log in</button><button className={mode === 'signup' ? 'active' : ''} onClick={() => setMode('signup')}>Create account</button></div><span className="kicker">{mode === 'signup' ? 'Start your workspace' : 'Welcome back'}</span><h2>{mode === 'signup' ? 'Create your workspace' : 'Pick up where you left off'}</h2><p className="muted">{mode === 'signup' ? 'Your profile will power every recommendation.' : 'Your research history and creator profile are ready.'}</p><form onSubmit={submit}><label>Username<input required value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} autoComplete="username" /></label>{mode === 'signup' && <label>Email<input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} autoComplete="email" /></label>}<label>Password<input required minLength={8} type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} autoComplete={mode === 'signup' ? 'new-password' : 'current-password'} /></label><button className="button primary" disabled={busy}>{busy ? 'Working...' : mode === 'signup' ? 'Create account' : 'Log in'}</button><p className="error-text">{error}</p></form></section></main>
}

function ProfileForm({ profile, onChange }: { profile: Profile; onChange: (profile: Profile) => void }) {
  const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false); const complete = [profile.niche, profile.platforms.length, profile.region].filter(Boolean).length
  const save = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setStatus('Saving...'); try { const saved = await request<Profile>('/agent/profile', { method: 'PATCH', headers: authHeaders(), body: JSON.stringify({ ...profile, creator_name: profile.creator_name || null, niche: profile.niche || null, region: profile.region || null }) }); onChange(profileForForm(saved)); setStatus('Profile saved') } catch (err) { setStatus(err instanceof Error ? err.message : 'Unable to save profile') } finally { setBusy(false) } }
  return <form onSubmit={save} className="profile-fields"><div className="profile-completion"><span>Profile completeness</span><strong className={complete === 3 ? 'complete' : ''}>{complete}/3 required</strong></div><label>Creator name<input value={profile.creator_name || ''} onChange={(event) => onChange({ ...profile, creator_name: event.target.value })} placeholder="Optional" /></label><label>Niche<input value={profile.niche || ''} onChange={(event) => onChange({ ...profile, niche: event.target.value })} placeholder="AI, fitness, finance..." /></label><label>Platforms<input value={profile.platforms.join(', ')} onChange={(event) => onChange({ ...profile, platforms: event.target.value.split(',').map((item) => item.trim()).filter(Boolean) })} placeholder="YouTube, Instagram, TikTok" /></label><label>Region<input value={profile.region || ''} onChange={(event) => onChange({ ...profile, region: event.target.value })} placeholder="India, United States..." /></label><div className="field-row"><label>Audience size<input type="number" min="0" value={profile.audience_size ?? ''} onChange={(event) => onChange({ ...profile, audience_size: event.target.value === '' ? null : Number(event.target.value) })} /></label><label>Average views<input type="number" min="0" value={profile.average_views ?? ''} onChange={(event) => onChange({ ...profile, average_views: event.target.value === '' ? null : Number(event.target.value) })} /></label></div><label>Engagement rate (%)<input type="number" min="0" step="0.01" value={profile.engagement_rate ?? ''} onChange={(event) => onChange({ ...profile, engagement_rate: event.target.value === '' ? null : Number(event.target.value) })} /></label><button className="button primary" disabled={busy}>{busy ? 'Saving...' : 'Save changes'}</button><p className="form-status">{status}</p></form>
}

function ProfilePage({ profile, onChange }: { profile: Profile; onChange: (profile: Profile) => void }) { return <PageFrame eyebrow="Your signal source" title="Creator profile" subtitle="This profile persists across every conversation and shapes opportunity relevance."><div className="profile-layout"><section className="panel profile-about"><span className="profile-avatar large">{(profile.creator_name || 'A').slice(0, 1).toUpperCase()}</span><h3>{profile.creator_name || 'Your creator identity'}</h3><p>{profile.niche || 'Add your niche to start tailoring signals.'}</p><div className="tag-row">{profile.platforms.map((platform) => <span className="tag" key={platform}>{platform}</span>)}</div></section><section className="panel"><div className="panel-heading"><div><span className="kicker">Persistent state</span><h3>Edit your profile</h3></div></div><ProfileForm profile={profile} onChange={onChange} /></section></div></PageFrame> }

function PageFrame({ eyebrow, title, subtitle, children }: { eyebrow: string; title: string; subtitle: string; children: ReactNode }) { return <div className="page-content"><span className="kicker dark">{eyebrow}</span><h1 className="page-title">{title}</h1><p className="page-subtitle">{subtitle}</p>{children}</div> }
function StatCard({ value, label, tone = '' }: { value: string; label: string; tone?: string }) { return <div className="stat-card"><strong className={tone}>{value}</strong><span>{label}</span></div> }
function SignalCard({ company, description, confidence, score, tone = 'green' }: { company: string; description: string; confidence: string; score: string; tone?: string }) { return <article className="signal-card"><div className="signal-top"><div className="company-mark">{company.slice(0, 1)}</div><div><h3>{company}</h3><p>{description}</p></div><span className={`confidence ${tone}`}>{confidence}</span><strong className="score">{score}</strong></div><div className="signal-meta"><span>Why you</span><span>Why now</span></div><div className="signal-actions"><DisabledButton>Research brand</DisabledButton><DisabledButton className="button primary">Evaluate fit</DisabledButton></div></article> }
function OverviewPage({ profile, onNavigate }: { profile: Profile; onNavigate: (page: Page) => void }) { return <PageFrame eyebrow={`Good afternoon, ${profile.creator_name || 'creator'}.`} title="Your deal desk" subtitle="Your creator business has active commercial signals worth exploring."><div className="stats-grid"><StatCard value="12" label="Active signals" /><StatCard value="4" label="Researching" tone="blue" /><StatCard value="3" label="Strong fits" tone="green" /></div><section className="attention panel"><div className="panel-heading"><div><span className="kicker">Needs your attention</span><h2>One promising signal</h2></div><button className="text-button" onClick={() => onNavigate('opportunities')}>View all →</button></div><SignalCard company="ElevenLabs" description="AI voice and audio technology" confidence="STRONG MATCH" score="91/100" /></section><div className="section-heading page-section-heading"><div><span className="kicker dark">Recent signals</span><h2>What is moving in your market</h2></div><DisabledButton>Discover new signals</DisabledButton></div><div className="table-list"><div><span className="company-mark small">A</span><strong>Adobe</strong><span>Product launch</span><span className="confidence green">HIGH</span><time>2h ago</time></div><div><span className="company-mark small">C</span><strong>Canva</strong><span>Affiliate activity</span><span className="confidence green">HIGH</span><time>5h ago</time></div><div><span className="company-mark small">D</span><strong>Descript</strong><span>Creator campaign</span><span className="confidence amber">MEDIUM</span><time>1d ago</time></div></div></PageFrame> }

function OpportunitiesPage() { return <PageFrame eyebrow="Commercial signals" title="Opportunities" subtitle="Find timely companies and partnership signals matched to your creator profile."><div className="toolbar"><div className="filter-tabs"><button className="active">All 12</button><DisabledButton>High confidence 5</DisabledButton><DisabledButton>Explicit 3</DisabledButton><DisabledButton>New 6</DisabledButton></div><DisabledButton>Sort by confidence⌄</DisabledButton></div><div className="signal-stack"><SignalCard company="ElevenLabs" description="AI voice and audio technology" confidence="HIGH" score="91" /><SignalCard company="Adobe" description="Creator ecosystem and creative tools" confidence="HIGH" score="84" /><SignalCard company="Canva" description="Design and content creation" confidence="MEDIUM" score="72" tone="amber" /><SignalCard company="Descript" description="Audio-video editing for creators" confidence="MEDIUM" score="68" tone="amber" /></div></PageFrame> }
function ResearchPage() { return <PageFrame eyebrow="Deep brand intelligence" title="Research" subtitle="Research jobs and completed brand intelligence will appear here."><section className="research-card panel"><div className="research-brand"><div className="company-mark large-mark">E</div><div><h2>ElevenLabs</h2><p>Deep brand research in progress</p></div><span className="status-pill">Completed</span></div><div className="progress-line"><span style={{ width: '94%' }} /></div><div className="research-grid"><div><span className="kicker dark">Research details</span><p>Company overview, creator activity, partnership signals, and requirements.</p></div><div><span className="kicker dark">Confidence</span><strong>94%</strong><p>Strong source coverage</p></div></div><div className="research-actions"><DisabledButton>View research</DisabledButton><DisabledButton>Research another brand</DisabledButton></div></section></PageFrame> }
function FitPage() { return <PageFrame eyebrow="Creator ↔ brand" title="Fit analysis" subtitle="Compare audience, content, market, partnership, and timing fit."><section className="fit-hero panel"><div className="fit-score">91</div><div><span className="kicker dark">Strong match</span><h2>ElevenLabs</h2><p>AI voice and audio technology</p><div className="fit-bars"><span>Audience fit <i style={{ width: '94%' }} /></span><span>Content fit <i style={{ width: '88%' }} /></span><span>Market fit <i style={{ width: '82%' }} /></span><span>Timing fit <i style={{ width: '90%' }} /></span></div></div></section><div className="two-column"><section className="panel"><h3>Why DealPilot recommends this</h3><ul className="check-list"><li>Strong creator relevance</li><li>Clear content alignment</li><li>Current commercial signal</li></ul></section><section className="panel"><h3>Concerns</h3><ul className="warning-list"><li>Sponsorship budget unknown</li><li>Partnership requirements not verified</li></ul></section></div></PageFrame> }

function ChatPage({ conversations, onRefresh }: { conversations: Conversation[]; onRefresh: () => void }) {
  const [session, setSession] = useState(localStorage.getItem(storage.session)); const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(''); const [busy, setBusy] = useState(false)
  const loadMessages = async (id: string | null) => { if (!id) { setMessages([]); return } try { setMessages(await request<Message[]>(`/agent/sessions/${encodeURIComponent(id)}/messages`, { headers: authHeaders() })) } catch { localStorage.removeItem(storage.session); setSession(null) } }
  useEffect(() => { void loadMessages(localStorage.getItem(storage.session)) }, [])
  const select = (id: string) => { localStorage.setItem(storage.session, id); setSession(id); void loadMessages(id) }; const newChat = () => { localStorage.removeItem(storage.session); setSession(null); setMessages([]) }
  const send = async (value: string) => { const message = value.trim(); if (!message || busy) return; setInput(''); setBusy(true); setMessages((current) => [...current, { role: 'user', content: message }, { role: 'assistant', content: 'Researching...' }]); try { let id = session; if (!id) { const created = await request<{ session_id: string }>('/agent/sessions', { method: 'POST', headers: authHeaders() }); id = created.session_id; setSession(id); localStorage.setItem(storage.session, id) } const result = await request<{ response: ResponsePayload }>(`/agent/sessions/${encodeURIComponent(id)}/messages`, { method: 'POST', headers: authHeaders(), body: JSON.stringify({ message }) }); setMessages((current) => [...current.slice(0, -1), { role: 'assistant', content: responseText(result.response) }]); onRefresh() } catch (err) { setMessages((current) => [...current.slice(0, -1), { role: 'assistant', content: `Unable to reach DealPilot: ${err instanceof Error ? err.message : 'unknown error'}` }]) } finally { setBusy(false) } }
  return <div className="chat-page"><div className="chat-toolbar"><div><span className="kicker dark">Conversation workspace</span><h2>Ask DealPilot</h2></div><button className="button secondary" onClick={newChat}>+ New conversation</button></div><div className="chat-history">{messages.length === 0 ? <div className="chat-empty"><span className="kicker dark">Your deal desk</span><h1>What should we explore next?</h1><p>Ask about sponsors, brands, creator campaigns, affiliate programs, or partnership fit.</p></div> : messages.map((message, index) => <article className={`chat-message ${message.role}`} key={`${message.created_at || index}-${index}`}><span className="message-author">{message.role === 'user' ? 'You' : 'DealPilot'}</span><div className="message-body">{message.role === 'assistant' ? <div dangerouslySetInnerHTML={{ __html: markdownHtml(message.content) }} /> : message.content}</div></article>)}</div><form className="chat-composer" onSubmit={(event) => { event.preventDefault(); void send(input) }}><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask DealPilot anything..." disabled={busy} /><button className="send-button" disabled={busy || !input.trim()}>Send ↗</button></form><div className="chat-conversation-strip"><span>{conversations.length} saved conversations</span>{conversations.slice(0, 4).map((conversation) => <button key={conversation.session_id} className={conversation.session_id === session ? 'active' : ''} onClick={() => select(conversation.session_id)}>Conversation · {new Date(conversation.created_at).toLocaleDateString()}</button>)}</div></div>
}
function SettingsPage({ user }: { user: User }) { return <PageFrame eyebrow="Workspace controls" title="Settings" subtitle="Account and preference controls will live here as the workspace expands."><section className="panel settings-card"><span className="kicker dark">Account</span><h3>{user.email || user.username}</h3><label>Email<input disabled value={user.email || ''} /></label><div className="settings-actions"><DisabledButton>Change password</DisabledButton><DisabledButton>Delete account</DisabledButton></div></section></PageFrame> }

function Sidebar({ page, setPage, user, profile, onLogout, onProfile }: { page: Page; setPage: (page: Page) => void; user: User; profile: Profile; onLogout: () => void; onProfile: () => void }) { const items: { id: Page; label: string; icon: string }[] = [{ id: 'overview', label: 'Overview', icon: '⌂' }, { id: 'opportunities', label: 'Opportunities', icon: '✦' }, { id: 'research', label: 'Research', icon: '◌' }, { id: 'fit', label: 'Fit', icon: '◒' }, { id: 'conversations', label: 'Conversations', icon: '▤' }]; return <aside className="product-sidebar"><Logo /><nav className="main-nav">{items.map((item) => <button className={page === item.id ? 'active' : ''} key={item.id} onClick={() => setPage(item.id)}><Icon>{item.icon}</Icon>{item.label}</button>)}</nav><div className="sidebar-spacer" /><nav className="secondary-nav"><button className={page === 'profile' ? 'active' : ''} onClick={onProfile}><Icon>◎</Icon>Profile</button><button className={page === 'settings' ? 'active' : ''} onClick={() => setPage('settings')}><Icon>⚙</Icon>Settings</button></nav><button className="user-chip" onClick={onProfile}><span>{(profile.creator_name || user.username).slice(0, 1).toUpperCase()}</span><div><strong>{profile.creator_name || user.username}</strong><small>{profile.niche || 'Complete profile'}</small></div><b>⌄</b></button><button className="sidebar-logout" onClick={onLogout}>Log out</button></aside> }

function AppShell({ user, profile, setProfile, onLogout }: { user: User; profile: Profile; setProfile: (profile: Profile) => void; onLogout: () => void }) {
  const [page, setPage] = useState<Page>('overview'); const [conversations, setConversations] = useState<Conversation[]>([])
  const refreshConversations = async () => { try { setConversations(await request<Conversation[]>('/agent/sessions', { headers: authHeaders() })) } catch { setConversations([]) } }
  useEffect(() => { const timer = window.setTimeout(() => { void refreshConversations() }, 0); return () => window.clearTimeout(timer) }, [])
  let content: ReactNode
  if (page === 'overview') content = <OverviewPage profile={profile} onNavigate={setPage} />
  if (page === 'opportunities') content = <OpportunitiesPage />
  if (page === 'research') content = <ResearchPage />
  if (page === 'fit') content = <FitPage />
  if (page === 'conversations') content = <ChatPage conversations={conversations} onRefresh={refreshConversations} />
  if (page === 'profile') content = <ProfilePage profile={profile} onChange={setProfile} />
  if (page === 'settings') content = <SettingsPage user={user} />
  return <div className="product-shell"><Sidebar page={page} setPage={setPage} user={user} profile={profile} onLogout={onLogout} onProfile={() => setPage('profile')} /><main className="product-main"><header className="topbar"><div className="topbar-title"><span className="status-dot" />DealPilot workspace</div><div className="topbar-actions"><DisabledButton className="icon-button">⌕</DisabledButton><DisabledButton className="icon-button">♧</DisabledButton><button className="top-avatar" onClick={() => setPage('profile')}>{(profile.creator_name || user.username).slice(0, 1).toUpperCase()}</button></div></header>{content}</main></div>
}

export default function App() { const [user, setUser] = useState<User | null>(null); const [profile, setProfile] = useState<Profile>(emptyProfile); const [loading, setLoading] = useState(true); const loadProfile = async () => { try { setProfile(profileForForm(await request<Profile>('/agent/profile', { headers: authHeaders() }))) } catch { setProfile(emptyProfile) } }; useEffect(() => { const timer = window.setTimeout(() => { if (!localStorage.getItem(storage.token)) { setLoading(false); return } request<User>('/auth/me', { headers: authHeaders() }).then((current) => { setUser(current); return loadProfile() }).catch(() => localStorage.clear()).finally(() => setLoading(false)) }, 0); return () => window.clearTimeout(timer) }, []); const logout = () => { localStorage.clear(); setUser(null); setProfile(emptyProfile) }; if (loading) return <div className="loading-screen">Loading DealPilot...</div>; return user ? <AppShell user={user} profile={profile} setProfile={setProfile} onLogout={logout} /> : <AuthScreen onLogin={(current) => { setUser(current); void loadProfile() }} /> }
